apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyma-mcp-clusterbinding
  labels:
    app: kyma-mcp-server
subjects:
  - kind: ServiceAccount
    name: kyma-mcp-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: kyma-mcp-clusterrole
  apiGroup: rbac.authorization.k8s.io
