apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyma-mcp-clusterrole
  labels:
    app: kyma-mcp-server
rules:
  - apiGroups: [""] # Core API group
    resources: ["pods"]
    verbs:
      - "create"
      - "list"
      - "get"
      - "watch"
      - "delete"
  - apiGroups: [""] # Core API group
    resources: ["namespaces"]
    verbs:
      - "get"
      - "list"
      - "create"
