apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyma-mcp-clusterrole
  labels:
    app: kyma-mcp-server
rules:
  - apiGroups: ["*"] # Core API group
    resources: ["*"]
    verbs:
      - "create"
      - "list"
      - "get"
      - "watch"
      - "delete"
      - "patch"
  - apiGroups: ["apps"] # Apps API group
    resources: ["deployments", "replicasets"]
    verbs:
      - "create"
      - "list"
      - "get"
      - "watch"
      - "delete"
      - "patch"
  - apiGroups: [""] # Core API group
    resources: ["namespaces"]
    verbs:
      - "get"
      - "list"
      - "create"
