apiVersion: v1
kind: Service
metadata:
  name: kyma-mcp-server-svc
  namespace: default
  labels:
    app: kyma-mcp-server
spec:
  # This selector tells the Service to find pods
  # with the label "app: kyma-mcp-server".
  selector:
    app: kyma-mcp-server

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
